"""Exports ranked proxy results into every required output format."""

from __future__ import annotations

import csv
import json
import logging
import math
import os
import tempfile
from io import StringIO
from pathlib import Path
from typing import List

from config.loader import OutputConfig
from utils.models import ProxyResult

logger = logging.getLogger("mtselector.exporter")


def eligible_results(results: List[ProxyResult], output_cfg: OutputConfig) -> List[ProxyResult]:
    return [
        r
        for r in results
        if r.successes > 0
        and math.isfinite(r.score)
        and r.score >= output_cfg.min_score
        and r.avg_latency_ms is not None
        and math.isfinite(r.avg_latency_ms)
        and 0 <= r.avg_latency_ms <= output_cfg.max_latency_ms
    ]


class Exporter:
    def __init__(self, output_cfg: OutputConfig):
        self.output_cfg = output_cfg
        self.folder = Path(output_cfg.folder)
        self.folder.mkdir(parents=True, exist_ok=True)

    def _filtered(self, results: List[ProxyResult]) -> List[ProxyResult]:
        return eligible_results(results, self.output_cfg)

    def _write(self, filename: str, text: str) -> Path:
        if Path(filename).name != filename or filename in ("", ".", ".."):
            raise ValueError("Export filename must be a filename inside the output directory")
        path = self.folder / filename
        temporary = None
        try:
            with tempfile.NamedTemporaryFile(
                mode="w", encoding="utf-8", newline="", dir=self.folder, prefix=".revmamad-", delete=False
            ) as stream:
                temporary = Path(stream.name)
                stream.write(text)
            os.replace(temporary, path)
        finally:
            if temporary is not None:
                temporary.unlink(missing_ok=True)
        return path

    def export_json(self, results: List[ProxyResult], filename: str = "proxy.json") -> Path:
        data = [r.to_dict() for r in results]
        return self._write(filename, json.dumps(data, indent=2, allow_nan=False))

    def export_txt(self, results: List[ProxyResult], filename: str = "proxy.txt") -> Path:
        lines = [
            f"{'[' + r.proxy.server + ']' if ':' in r.proxy.server else r.proxy.server}:{r.proxy.port}:{r.proxy.secret}  # score={r.score:.3f}"
            for r in results
        ]
        return self._write(filename, "\n".join(lines) + ("\n" if lines else ""))

    def export_csv(self, results: List[ProxyResult], filename: str = "proxy.csv") -> Path:
        fieldnames = [
            "server",
            "port",
            "secret",
            "source",
            "score",
            "success_rate",
            "avg_latency_ms",
            "median_latency_ms",
            "jitter_ms",
            "stability",
            "timeout_rate",
            "last_failure_reason",
            "tg_link",
        ]
        with StringIO(newline="") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            for r in results:
                d = r.to_dict()
                writer.writerow({k: d.get(k) for k in fieldnames})
            return self._write(filename, f.getvalue())

    def export_telegram_links(self, results: List[ProxyResult], filename: str = "telegram_links.txt") -> Path:
        lines = [r.proxy.tg_link() for r in results]
        return self._write(filename, "\n".join(lines) + ("\n" if lines else ""))

    def export_top_n(self, results: List[ProxyResult], n: int) -> Path:
        if n < 1:
            raise ValueError("Top count must be positive")
        data = [r.to_dict() for r in results[:n]]
        return self._write(f"top{n}.json", json.dumps(data, indent=2, allow_nan=False))

    def export_best_n_readable(
        self, results: List[ProxyResult], n: int = 10, filename: str = "best10_links.txt"
    ) -> Path:
        """Human-friendly top-N file: rank, speed, and a ready-to-click tg:// link for each proxy.

        Use the same score/latency/endpoint order as top10.json and terminal output.
        """
        if n < 1:
            raise ValueError("Top count must be positive")
        healthy = self._filtered(results)
        from benchmark.scorer import rank

        top = rank(healthy)[:n]

        lines = [
            "Top {} Verified MTProto Proxies (up to {} requested)".format(len(top), n),
            "Generated by REVMAMAD",
            "=" * 60,
            "",
        ]
        for i, r in enumerate(top, 1):
            lines.append(
                f"#{i}  {r.proxy.server}:{r.proxy.port}\n"
                f"    Speed: {r.avg_latency_ms:.0f} ms   |   Success rate: {r.success_rate * 100:.0f}%   |   Score: {r.score * 100:.1f}%\n"
                f"    Link:  {r.proxy.tg_link()}\n"
            )

        if not top:
            lines.append("No healthy proxies found in the last run. Run `python main.py export` again later.")

        return self._write(filename, "\n".join(lines))

    def export_all(self, results: List[ProxyResult]) -> dict:
        ranked = self._filtered(results)
        from benchmark.scorer import rank

        ranked = rank(ranked)

        paths = {
            "json": str(self.export_json(ranked)),
            "txt": str(self.export_txt(ranked)),
            "csv": str(self.export_csv(ranked)),
            "telegram_links": str(self.export_telegram_links(ranked)),
        }
        for size in self.output_cfg.top_sizes:
            paths[f"top{size}"] = str(self.export_top_n(ranked, size))

        logger.info("Exported %d healthy proxies to %s", len(ranked), self.folder)
        return paths
