"""Exports ranked proxy results into every required output format."""
from __future__ import annotations

import csv
import json
import logging
from pathlib import Path
from typing import List

from config.loader import OutputConfig
from utils.models import ProxyResult

logger = logging.getLogger("mtselector.exporter")


class Exporter:
    def __init__(self, output_cfg: OutputConfig):
        self.output_cfg = output_cfg
        self.folder = Path(output_cfg.folder)
        self.folder.mkdir(parents=True, exist_ok=True)

    def _filtered(self, results: List[ProxyResult]) -> List[ProxyResult]:
        return [
            r
            for r in results
            if r.score >= self.output_cfg.min_score
            and (r.avg_latency_ms is None or r.avg_latency_ms <= self.output_cfg.max_latency_ms)
        ]

    def export_json(self, results: List[ProxyResult], filename: str = "proxy.json") -> Path:
        path = self.folder / filename
        data = [r.to_dict() for r in results]
        path.write_text(json.dumps(data, indent=2), encoding="utf-8")
        return path

    def export_txt(self, results: List[ProxyResult], filename: str = "proxy.txt") -> Path:
        path = self.folder / filename
        lines = [f"{r.proxy.server}:{r.proxy.port}:{r.proxy.secret}  # score={r.score:.3f}" for r in results]
        path.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")
        return path

    def export_csv(self, results: List[ProxyResult], filename: str = "proxy.csv") -> Path:
        path = self.folder / filename
        fieldnames = [
            "server",
            "port",
            "secret",
            "source",
            "score",
            "success_rate",
            "avg_latency_ms",
            "median_latency_ms",
            "jitter_ms",
            "stability",
            "timeout_rate",
            "last_failure_reason",
            "tg_link",
        ]
        with path.open("w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            for r in results:
                d = r.to_dict()
                writer.writerow({k: d.get(k) for k in fieldnames})
        return path

    def export_telegram_links(self, results: List[ProxyResult], filename: str = "telegram_links.txt") -> Path:
        path = self.folder / filename
        lines = [r.proxy.tg_link() for r in results]
        path.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")
        return path

    def export_top_n(self, results: List[ProxyResult], n: int) -> Path:
        path = self.folder / f"top{n}.json"
        data = [r.to_dict() for r in results[:n]]
        path.write_text(json.dumps(data, indent=2), encoding="utf-8")
        return path

    def export_best_n_readable(self, results: List[ProxyResult], n: int = 10, filename: str = "best10_links.txt") -> Path:
        """Human-friendly top-N file: rank, speed, and a ready-to-click tg:// link for each proxy.

        Sorted purely by speed (avg latency) among already-healthy, ranked proxies, so the
        fastest proxy is always #1 regardless of small score-weighting differences.
        """
        path = self.folder / filename
        healthy = [r for r in results if r.success_rate > 0 and r.avg_latency_ms is not None]
        healthy.sort(key=lambda r: r.avg_latency_ms)
        top = healthy[:n]

        lines = [
            "Top {} Fastest Working MTProto Proxies".format(len(top)),
            "Generated by Telegram MTProto Smart Selector",
            "=" * 60,
            "",
        ]
        for i, r in enumerate(top, 1):
            lines.append(
                f"#{i}  {r.proxy.server}:{r.proxy.port}\n"
                f"    Speed: {r.avg_latency_ms:.0f} ms   |   Success rate: {r.success_rate * 100:.0f}%   |   Score: {r.score * 100:.1f}%\n"
                f"    Link:  {r.proxy.tg_link()}\n"
            )

        if not top:
            lines.append("No healthy proxies found in the last run. Run `python main.py export` again later.")

        path.write_text("\n".join(lines), encoding="utf-8")
        return path

    def export_all(self, results: List[ProxyResult]) -> dict:
        ranked = self._filtered(results)
        ranked.sort(key=lambda r: r.score, reverse=True)

        paths = {
            "json": str(self.export_json(ranked)),
            "txt": str(self.export_txt(ranked)),
            "csv": str(self.export_csv(ranked)),
            "telegram_links": str(self.export_telegram_links(ranked)),
        }
        for size in self.output_cfg.top_sizes:
            paths[f"top{size}"] = str(self.export_top_n(ranked, size))

        logger.info("Exported %d healthy proxies to %s", len(ranked), self.folder)
        return paths
