"""Atomic web proxy exports with the shared composite-score ordering."""

from __future__ import annotations

import csv
from io import StringIO
from pathlib import Path

from benchmark.scorer import rank
from exporter.exporter import Exporter
from utils.models import ProxyResult


class WebExporter(Exporter):
    def export_txt(self, results: list[ProxyResult], filename: str = "proxy.txt") -> Path:
        lines = [f"{r.proxy.uri()}  # score={r.score:.3f}" for r in results]
        return self._write(filename, "\n".join(lines) + ("\n" if lines else ""))

    def export_csv(self, results: list[ProxyResult], filename: str = "proxy.csv") -> Path:
        fields = [
            "server",
            "port",
            "protocol",
            "source",
            "uri",
            "score",
            "success_rate",
            "avg_latency_ms",
            "median_latency_ms",
            "jitter_ms",
            "stability",
            "timeout_rate",
            "last_failure_reason",
        ]
        with StringIO(newline="") as stream:
            writer = csv.DictWriter(stream, fieldnames=fields)
            writer.writeheader()
            for result in results:
                row = result.to_dict()
                writer.writerow({key: row.get(key) for key in fields})
            return self._write(filename, stream.getvalue())

    def export_proxy_links(self, results: list[ProxyResult], filename: str = "proxy_links.txt") -> Path:
        lines = [result.proxy.uri() for result in results]
        return self._write(filename, "\n".join(lines) + ("\n" if lines else ""))

    def export_top_n(self, results: list[ProxyResult], n: int) -> Path:
        return super().export_top_n(rank(self._filtered(results)), n)

    def export_best_n_readable(
        self, results: list[ProxyResult], n: int = 10, filename: str = "best10_links.txt"
    ) -> Path:
        if n < 1:
            raise ValueError("Top count must be positive")
        top = rank(self._filtered(results))[:n]
        lines = [
            f"Top {len(top)} Verified Web Proxies (up to {n} requested)",
            "Generated by REVMAMAD",
            "=" * 60,
            "",
        ]
        for index, result in enumerate(top, 1):
            lines.append(
                f"#{index}  {result.proxy.uri()}\n"
                f"    Latency: {result.avg_latency_ms:.0f} ms | "
                f"Success: {result.success_rate * 100:.0f}% | "
                f"Score: {result.score * 100:.1f}%\n"
            )
        if not top:
            lines.append("No verified web proxies in the last completed scan.")
        return self._write(filename, "\n".join(lines))

    def export_all(self, results: list[ProxyResult]) -> dict:
        ranked = rank(self._filtered(results))
        paths = {
            "json": str(self.export_json(ranked)),
            "txt": str(self.export_txt(ranked)),
            "csv": str(self.export_csv(ranked)),
            "proxy_links": str(self.export_proxy_links(ranked)),
        }
        for size in self.output_cfg.top_sizes:
            paths[f"top{size}"] = str(self.export_top_n(ranked, size))
        return paths
